# netlify.toml (root of repo)

[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  
# existing build section stays above
# ...
[[redirects]]
  from = "/thanks"
  to = "/thanks.html"
  status = 200
